# This is a basic workflow to help you get started with Actions

name: Build-OrangePi

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  VERSION: Workspace

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: 查看空间
      if: (!cancelled())
      run: df -hT
    - name: 删除无用文件
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        df -hT
    - name: Checkout
      uses: actions/checkout@main
    - name: 下载依赖
      run: |
        sudo apt-get update -y
        sudo apt full-upgrade -y
        sudo apt-get install -y git
    - name: 下载源码
      run: |
        git clone https://github.com/orangepi-xunlong/orangepi-build.git -b next Workspace
    - name: 配置编译选项
      run: |
        cd $VERSION
        ls
    - name: 编译 u-boot
      run: |
        cd $VERSION
        sudo ./build.sh BOARD=orangepizero3 BRANCH=next BUILD_OPT=u-boot
        ls output/debs/u-boot/
    - name: 编译Linux内核
      run: |
        cd $VERSION
        sudo ./build.sh BOARD=orangepizero3 BRANCH=next BUILD_OPT=kernel KERNEL_CONFIGURE=no
        ls output/debs/linux-*
    - name: 编译rootfs
      run: |
        cd $VERSION

    - name: 编译Linux镜像
      run: |
        cd $VERSION
        sudo ./build.sh BOARD=orangepizero3 BRANCH=next BUILD_OPT=image RELEASE=bullseye BUILD_MINIMAL=no BUILD_DESKTOP=yes KERNEL_CONFIGURE=yes
    - name: 查看空间
      if: (!cancelled())
      run: df -hT
    - name: 打包
      run: |
        cd $VERSION
#    - name: 上传
#      uses: actions/upload-artifact@main
#      #if: steps.organize.outputs.status == 'success' && !cancelled()
#      with:
#        name: kernel
#        path: kernel.zip
