# This is a basic workflow to help you get started with Actions

name: BuildLinux

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: 下载依赖
      run: |
        sudo apt-get update -y
        sudo apt full-upgrade -y
        sudo apt-get install -y git fakeroot build-essential ncurses-dev xz-utils libssl-dev bc flex libelf-dev bison
    - name: 下载源码
      run: |
        wget https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.14.1.tar.xz
        tar xvf linux-5.14.1.tar.xz
    - name: 配置内核
      run: |
        cd linux-5.14.1
        #cp -v /boot/config-$(uname -r) .config
        cp -v ../config/kernel.config .config
        scripts/config --set-str SYSTEM_TRUSTED_KEYS ""
        scripts/config --disable SYSTEM_REVOCATION_KEYS
        scripts/config --disable CONFIG_DEBUG_INFO_BTF
        #make defconfig
    - name: 编译
      run: |
        cd linux-5.14.1
        make -j$(nproc) ||  make -j1 V=s
#     - name: make bzImage
#       run: |
#         cd linux-5.14.1
#         #make bzImage -j$(nproc)
#         make modules -j$(nproc)
    - name: 编译结束
      run: |
        echo "*****done*****"
        cd linux-5.14.1
        #sudo make modules_install
        #sudo make install

