name: GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: test1
      run: |
        echo "start"
        git clone https://github.com/coolsnowwolf/lede
        cd lede
        ls
